// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUmdYc8wCUkK7kqvfwdPYx9fFM2YQ9DvQ',
    appId: '1:407942606863:web:ae6dae6fe8990ceac8337a',
    messagingSenderId: '407942606863',
    projectId: 'fir-flutter-crud-7dc6e',
    authDomain: 'fir-flutter-crud-7dc6e.firebaseapp.com',
    storageBucket: 'fir-flutter-crud-7dc6e.appspot.com',
    measurementId: 'G-PK71SRH4XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_BAO_IJdw63-lNC_-XtWVAZYVZNvQatE',
    appId: '1:407942606863:android:2a058d339cf0e019c8337a',
    messagingSenderId: '407942606863',
    projectId: 'fir-flutter-crud-7dc6e',
    storageBucket: 'fir-flutter-crud-7dc6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCExWM0GUjHa4oiihaPwuygKgyKUM5b-8w',
    appId: '1:407942606863:ios:15b6e45832f8d4d2c8337a',
    messagingSenderId: '407942606863',
    projectId: 'fir-flutter-crud-7dc6e',
    storageBucket: 'fir-flutter-crud-7dc6e.appspot.com',
    iosBundleId: 'com.example.firebaseFlutterCrud',
  );
}
